# Site
title: Anthony Mun
sitename: Anthony Mun
description: My name is Anthony Mun and I'm a Software Engineer.
url: "https://www.hrmun.com"

# Assets
sass:
  sass_dir: /assets/_sass
  style: :compressed

# Collections
collections:
  - section
  
# Plugins
plugins:
  - jekyll-seo-tag

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME